### ISSUE TITLE
気圧機能つける

### ISSUE THREAD

**Issue by nullnyat** [nullnyat/nullcat-chan#14]

**Comment by nullnyat** [comment]
https://zenn.dev/shuzon/articles/8ce0d4bafea9e28d9edd

**Comment by nullnyat** [comment]
一時間ごとに気圧の状況を取得してノート
@ nullcat きあつ　で今の状況をリプライ

**Comment by hijiki02** [comment]
つくった！
https://github.com/nullnyat/nullcat-chan/commit/622ec3369b70265122e87bc0e95c8a000a87dd6a
