### ISSUE TITLE
時報機能付ける

### ISSUE THREAD

**Issue by nullnyat** [nullnyat/nullcat-chan#8]

**Comment by nullnyat** [comment]
https://github.com/Leies-202/mis-php-list/tree/master/time

**Comment by nullnyat** [comment]
やっぱいらない

**Comment by hijiki02** [comment]
やっぱいるらしい

**Comment by hijiki02** [comment]
できた！https://github.com/nullnyat/nullcat-chan/commit/aa09bb66cd1b75e7c98ae4dd8fc76e4454e2d955
